# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='emailable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='textable',
            field=models.BooleanField(default=False),
        ),
    ]
