# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
